Implement JobApplicationNotes
akucintavalent/job-tracker pull request #54
Opened 2024-08-24 05:46 UTC by gefasim

Contains DB and API changes

1. Added new table - `job_application_notes`
2. Added new CRUD endpoints for JobApplicationNotes
3. JobApplicationNotes added into GET `/job-applications` endpoints

2024-08-24 19:47 UTC, akucintavalent requested changes

2024-08-24 19:47 UTC, akucintavalent commented on src/utils/array.extensions.ts
> +export {};
I think this is not necessary.

2024-08-24 19:47 UTC, akucintavalent commented on src/utils/array.extensions.ts
> +  };
I don't think you need to pass `this` as an argument to the function it must be accessible inside the function already.

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-applications/job-applications.service.ts
>        throw new BadRequestException("Board column doesn't exists");
exist

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-applications/job-applications.mapper.ts
>      dto.updatedAt = entity.updatedAt;
In such places you can use lodash library, and you can do something like

```ts
Object.assign(dto, _.pick(entity, ['id', 'title', 'companyName', 'description', 'createdAt', 'updatedAt']))
```

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-applications/job-applications.mapper.ts
>      dto.updatedAt = entity.updatedAt;
Although to be honest i don't really understand why we are having these mappers :D

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/job-application-notes.service.ts
> +    await this.jobApplicationNotesRepository.upsert(noteEntities, ['id']);
I don't understand how this works

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/job-application-notes.service.ts
> +    const isJobApplicationExists = await this.jobApplicationsRepository.existsBy({
please remove `is` from the name

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/job-application-notes.service.ts
> +      throw new BadRequestException("JobApplication doesn't exists");
`exist`, without `s`

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/job-application-notes.mapper.ts
> +    dto.updatedAt = entity.updatedAt;
```ts
Object.assign(dto, _.pick(entity, ['id', 'content', 'order', 'createdAt', 'updatedAt']))
```

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/job-application-notes.controller.ts
> +    return this.jobApplicationNotesService.create(jobApplicationNote, user.userId);
In other places you do `{ userId }: AuthUserDto`. Try to be a little bit more consistent

2024-08-24 19:47 UTC, akucintavalent commented on src/modules/job-application-notes/dtos/update-job-application-note.dto.ts
> +  content: string | null;
I think `@IsOptional()` means you should use `content?: string | null`

2024-08-25 05:09 UTC, gefasim commented on src/utils/array.extensions.ts
> +export {};
It is required

2024-08-25 05:12 UTC, gefasim commented on src/utils/array.extensions.ts
> +  };
I'm leaving for readability

2024-08-25 05:14 UTC, gefasim commented on src/modules/job-application-notes/job-application-notes.service.ts
> +    await this.jobApplicationNotesRepository.upsert(noteEntities, ['id']);
upsert - Inserts a new entity or array of entities unless they already exist in which case they are updated instead
https://orkhan.gitbook.io/typeorm/docs/repository-api

2024-08-25 12:41 UTC, akucintavalent approved these changes

2024-08-25 12:44 UTC, merged